### ISSUE TITLE
Number of projects

### ISSUE THREAD

**Issue by JohannesKonings** [dotabap/dotabap.github.io#22]
The number of projects would be interesting and could look like this:

![image](https://user-images.githubusercontent.com/14806640/42693708-43353c20-86b0-11e8-9662-fb5ef119d97c.png)

**Comment by JohannesKonings** [comment]
better?
![image](https://user-images.githubusercontent.com/14806640/42694361-74b10476-86b2-11e8-81fe-f26815cddf91.png)

**Comment by larshp** [comment]
yeah

**Comment by JohannesKonings** [comment]
done with https://github.com/dotabap/dotabap.github.io/pull/23
