### ISSUE TITLE
Can't be displayed in abapGit - loading screen stuck because of syntax error in script.js

### ISSUE THREAD

**Issue by bigld** [dotabap/dotabap.github.io#25]
The arrow function in function ajax causes this error - so it can't be displayed in abapGit SAP Gui 4 Windows

**Comment by larshp** [comment]
as far as I remember, abapGit shows https://github.com/dotabap/dotabap.github.io/blob/master/explore.html ?

**Comment by larshp** [comment]
yea, or try opening in new window, however not sure if it works with the integrated browser

https://www.w3schools.com/tags/att_a_target.asp

**Comment by bigld** [comment]
new window doesn't work!
PR in work

**Comment by bigld** [comment]
closing
